main: de.simonsator.partyandfriends.spigot.main.Main
name: FriendsAPIForPartyAndFriends
version: ${project.version}
author: Simonsator
load: STARTUP
softdepend: [MVdWPlaceholderAPI, PlaceholderAPI]
api-version: 1.13